name: Rubocop linting
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - feature/*
      - "*-stable"
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Rubocop linting
        run: bundle install rubocop && rubocop
      - name: ERB files linting
        run: bundle install erblint && bundle exec erblint --lint-all
